# Generated by Django 5.2.9 on 2026-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("accident_date", models.DateField()),
                ("accident_time", models.TimeField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Two Wheeler", "Two Wheeler"),
                            ("Car", "Car"),
                            ("Truck", "Truck"),
                            ("Bus", "Bus"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Minor", "Minor"),
                            ("Major", "Major"),
                            ("Fatal", "Fatal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "accident_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="accident_images/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Verified", "Verified"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
