# Generated by Django 5.2.9 on 2026-02-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accident",
            name="accident_image",
        ),
        migrations.AddField(
            model_name="accident",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="severity",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="accident",
            name="status",
            field=models.CharField(default="Pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="accident",
            name="vehicle_type",
            field=models.CharField(max_length=20),
        ),
    ]
