# Generated by Django 5.2.9 on 2026-02-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0002_remove_accident_accident_image_accident_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="accident_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
