# Generated by Django 5.2.9 on 2026-02-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0003_alter_accident_accident_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="accident_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
